### ISSUE TITLE
Create a helper tool to upgrade individual apps

### ISSUE THREAD

**Issue by jtimberman** [chef/appbundler#15]
appbundler manages apps in `/opt/{chef,chefdk}/embedded/apps`. It would be nice to have a tool that can seamlessly upgrade these applications, so end users can optionally test out new versions without the need to download and install the omnibus package.

Note it will still be recommended that users upgrade the whole package once available. This functionality would allow running test/development versions easier.

**Comment by lamont-granquist** [comment]
http://github.com/chef/appbundle-updater and http://github.com/chef/kitchen-appbundle-updater
