### ISSUE TITLE
Create way to install gems from source location, without needing to bundle

### ISSUE THREAD

**Issue by jmahowald** [chef/appbundler#17]
Per a conversation with @jdmundrawala and @fnichol at ChefConf:

In order to distribute tools to go with ChefDK to non ruby developers, it would be useful if there was a command to easily create an appbundled version of the tools. 

For example

   chef app gem specific install <source>

As I'm writing this I'm wondering if we could allow auto updates/pulls for added gems . .

**Comment by lamont-granquist** [comment]
that's most likely a chef-dk command that calls this, and there's considerable overlap with http://github.com/chef/appbundle-updater

**Comment by lamont-granquist** [comment]
closing this as having been open too long with little interest.  the use case is probably covered by appbundle-updater.  also most likely filed in the wrong repo and should have been opened against chef-dk.
