### ISSUE TITLE
Bundler as a dependency doesn't work

### ISSUE THREAD

**Issue by mikesimons** [chef/appbundler#4]
When bundler creates the lock file it omits itself from the resolved specs. This means that when appbundler tries to process the lock file it can't find the spec for bundler.

I'm not sure what the best resolution would be but the following strike me:

- Skip bundler (potentially leaves it floating in the bundled app)
- Default bundler to the current bundler version

Anything beyond that would require using or replicating the bundler constraint resolution I think.

Here are steps to reproduce:

Gemfile:
```
source 'https://rubygems.org'
gemspec
```

testing.gemspec:
```
Gem::Specification.new do |spec|
  spec.name          = "testing"
  spec.version       = '0'
  spec.summary       = 'testing'
  spec.executables   = 'testing'
  spec.authors       = [ 'mike' ]
  spec.add_dependency "bundler", ">= 1.5.2"
end
```

`mkdir bin && touch bin/testing`

`bundle install`

`appbundler . .`

The resulting Gemfile.lock looks like this:
```
PATH
  remote: .
  specs:
    testing (0)
      bundler (>= 1.5.2)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  testing!
```

**Comment by lamont-granquist** [comment]
#22
